### ISSUE TITLE
Working with Django signals

### ISSUE THREAD

**Issue by bgarcial** [camilonova/ama#1]
I don't know if my following case be a general purpose, or this could be apply to many people (probably) but I did want share with you:

I have a custom users schema in Django for work with roles or users type. 

I customize my User class that inherit of the AbstractUser class for add some fields to my User model due to my requirements demanded me. 

I create these another models for roles/profile users (medical, patient, physiotherapist) with their own fields or attributes

```
#models.py
```

![userrolesmodels](https://cloud.githubusercontent.com/assets/1211088/12054842/f7662f4c-aef4-11e5-86ba-23e64dcf83c6.png)

I want, each that an user is created, automatically (by  `post_save` signal action) be created their profile (MedicalProfile, PatientProfile, PhysiotherapistProfile) according to if their field checked (is_medical, is_patient, is_physiotherapist)

The inconvenient that I have is with my signal, due to, when I create an user via django admin, indicating that this user is medical (have the is_medical field/attribute checked in the user admin form) in my MedicalProfile model, their profile instance not is saved or don't created

I have been checking the situation through `ipdb` basic debug functions and I think so that when I create the user the compiler or the steps don't arrive to the section when I check if my user is medical (`if user.is_medical` code line)

```
@receiver(post_save, sender=settings.AUTH_USER_MODEL) 
def create_profile_for_new_user(sender, instance, created, **kwargs):
    user = instance
    if created:
        if user.is_medical:
            profile=MedicalProfile(user=instance)
            profile.save()`
```

This is my analysis about it using`ipdb` package. I did want share in this document https://docs.google.com/document/d/10KYInsTUVHFZw7nRkQS0-Z_oT0dHz8SYoP847BucPas/edit?usp=sharing and I would that yo can review it 

What alternatives can I have in this case?

I bring to you my apologies before, in case of the my question do not be suited or appropriated with the AMA philosophy or by the extense of my question. 

Any orientation  I will be grateful with you and will be appreciated

Thanks a lot.

**Comment by camilonova** [comment]
Actually best place to ask this will be at StackOverflow.

But...

I've read all the problem now and I must say the easiest and better way will be to override the save method on your User model. This way you will be 100% sure the profile gets created when you are adding a new User and it will work at the admin site or anywhere else, like your shell.

https://docs.djangoproject.com/en/1.9/topics/db/models/#overriding-model-methods

Usually I use signals when I don't need any type of data integrity.

Some code will be:

``` python
class User(AbstractUser):
    ...
    def save(self, *args, **kwargs):
        if self.is_medical:
            profile = MedialProfile(user=self)

        super(Blog, self).save(*args, **kwargs)
        profile.save()
```

Hope helps you, if you need more help please go to StackOverflow.

**Comment by bgarcial** [comment]
Hi Camilo, of course, I am agree with you, the post was too extense, my apologies.
Thanks for the ideas and orientation. Of anyway you did support me with that reference and idea of override model methods.  :)

I begin to check this situation
Thanks for your time and the response.
