### ISSUE TITLE
Colaborar en proyectos open source

### ISSUE THREAD

**Issue by ospcg** [camilonova/ama#8]
Camilo: Soy desarrollador, he conocido varios lenguajes pero en mi universidad nunca me enseñaron python, estoy aprendiendo django y me ha encantado, he conocido laravel y rails incluso otros como el  stack MEAN de javascript, pero me quedo con django. Me pregunto como colaborar en alguno de tus proyectos open source, ya que te vi en una meetup que está en el canal Pulsar MediaBlog de youtube, donde invitas a los desarrolladores a colaborar en proyectos open source de python o django, me encantaria aportar e ir aprendiendo a la vez, saludos desde Chile.

**Comment by camilonova** [comment]
@ospcg Oscar, que bueno que quieras colaborar en open source.

Puedes comenzar con este proyecto https://github.com/jazzband/django-axes

Si quieres puedes ver otros en https://github.com/jazzband/

Allí puedes comenzar fácilmente y puedo llegar a ayudarte si lo necesitas.

Saludos desde Bogotá

**Comment by ospcg** [comment]
Estimado, consulta básica para comenzar, un primer paso seria clonar el repositorio? He mirado los proyectos y la verdad parece q son avanzados para mí no sabría que hacer, pero tengo muchas ganas de aportar

**Comment by camilonova** [comment]
@ospcg Oscar el primer paso es leer el código y entender el proyecto, puedes ver si hace falta algo en la documentación para comenzar.
